/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.farmacia.gui;

import br.edu.map.farmacia.dao.FarmaciaDAO;

/**
 *
 * @author alina
 */
public class FarmaciaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FarmaciaJFrame
     */
    
    private FarmaciasJFrame parent;
    private FarmaciaDAO farmaciaDAO;
            
    FarmaciaJFrame(FarmaciasJFrame parent) {
        
        this.parent = parent;
        this.farmaciaDAO = new FarmaciaDAO();
        setTitle("Editar titulo");
        //MensagensUtil.setLocale(1);
        //setTitle(MensagensUtil.getMensagem(MensagensUtil.MSG_LABEL_EDITAR_TITULO));
        
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
