/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.farmacia.gui;

import br.edu.map.farmacia.dao.FarmaciaDAO;
import br.edu.map.farmacia.model.Farmacia;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alina
 */
public class FarmaciasJFrame extends javax.swing.JFrame {
    
    private FarmaciaDAO farmaciaDAO = new FarmaciaDAO();
    private Farmacia farmaciaSelecionada = new Farmacia();
    
    /**
     * Creates new form FarmaciasJFrame
     */
    public FarmaciasJFrame() {
        initComponents();
        preencherTabela(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFarmacias = new javax.swing.JLabel();
        labelBuscar = new javax.swing.JLabel();
        textFieldBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFarmacias = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        menuIdioma = new javax.swing.JMenuBar();
        labelIdioma = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFarmacias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelFarmacias.setText("Farmácias");
        getContentPane().add(labelFarmacias, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        labelBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBuscar.setText("Buscar:");
        getContentPane().add(labelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        textFieldBusca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscaActionPerformed(evt);
            }
        });
        textFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldBuscaKeyReleased(evt);
            }
        });
        getContentPane().add(textFieldBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 370, -1));

        tableFarmacias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableFarmacias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableFarmacias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFarmaciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFarmacias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 950, 290));

        buttonNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 80, -1));

        buttonEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 80, -1));

        buttonExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 80, -1));

        buttonSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 80, -1));

        labelIdioma.setText("Idioma");
        labelIdioma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuIdioma.add(labelIdioma);

        setJMenuBar(menuIdioma);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscaActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // TODO add your handling code here:
        
        try{
            if(farmaciaSelecionada != null){
                String nome = JOptionPane.showInputDialog(this,"editar nome");
                        //MensagensUtil.getMensagem(mensagensUtil.MSG_LABEL_EDITAR_NOME));
                String cnpj = JOptionPane.showInputDialog(this,"editar cnpj");
                
                //adicionar todas as opções de editar
                
                Farmacia f = new Farmacia(nome, cnpj);
                f.setCodigo(farmaciaSelecionada.getCodigo());
                
                farmaciaDAO.editar(f);
                
                preencherTabela(null);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro ao editar"
                    //MensagensUtil.getMensagem(mensagensUtil.MSG_ERRO_EDITAR)
                    );
        }
        
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        // TODO add your handling code here:
        
        FarmaciaJFrame janela = new FarmaciaJFrame(this);
        janela.setVisible(true);
        
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_buttonSairActionPerformed

    private void textFieldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldBuscaKeyReleased
        // TODO add your handling code here:
        
        try{
            String busca = textFieldBusca.getText();
            List<Farmacia> farmacias = farmaciaDAO.buscar(busca);
            preencherTabela(farmacias);
            
        } catch (Exception ex) {
            Logger.getLogger(FarmaciasJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_textFieldBuscaKeyReleased

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
        
        try{
            if (farmaciaSelecionada != null){
                 int op = JOptionPane.showConfirmDialog(this,
                         "excluir titulo"
                         //MensagensUtil.getMensagem(mensagensUtil.MSG_LABEL_EXCLUIR_TITULO)
                            +farmaciaSelecionada.getNome() + "?",
                         "excluir", 
                        // MensagensUtil.getMensagem(mensagensUtil.MSG_LABEL_EXCLUIR),
                        
                        JOptionPane.OK_CANCEL_OPTION);
                 
                 if(op == JOptionPane.OK_OPTION){
                     farmaciaDAO.excluir(farmaciaSelecionada);
                     farmaciaSelecionada = null;
                     preencherTabela(null);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro ao excluir"
                    //MensagensUtil.getMensagem(mensagensUtil.MSG_ERRO_EXCLUIR )
            );
        }
        
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void tableFarmaciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFarmaciasMouseClicked
        // TODO add your handling code here:
        try{ 
            JTable tabelaFarmacias = (JTable) evt.getSource();
            int linha = tabelaFarmacias.rowAtPoint(evt.getPoint());
            int codigo = (int) tabelaFarmacias.getModel().getValueAt(linha, 0);
        
            farmaciaSelecionada = farmaciaDAO.buscarPorCodigo(codigo);
        }catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro");
            //JOptionPane.showMessageDialog(this, MensagensUtil.getMensagem(MensagensUtil.MSG_ERRO_CLIQUE));
        }
        
    }//GEN-LAST:event_tableFarmaciasMouseClicked
    
    public void preencherTabela(List<Farmacia> lista) {
        try {

            List<Farmacia> farmacias = null;

            if (lista == null) {
                farmacias = farmaciaDAO.listar();
            } else {
                farmacias = lista;
            }

            DefaultTableModel model = new DefaultTableModel();

            model.setColumnCount(11);
            model.setColumnIdentifiers(
                    new String[]{"Código", "Nome", "CNPJ", "Telefone", "E-mail",
                        "Cidade", "Estado", "CEP", "Rua", "N°", "Bairro"});
            
            
            model.setRowCount(farmacias.size());

            for (int i = 0; i < farmacias.size(); i++) {

                Farmacia f = farmacias.get(i);

                model.setValueAt(f.getCodigo(), i, 0);
                model.setValueAt(f.getNome(), i, 1);
                model.setValueAt(f.getCnpj(), i, 2);
                model.setValueAt(f.getTelefone(), i, 3);
                model.setValueAt(f.getEmail(), i, 4);
                model.setValueAt(f.getId_endereco().getCidade(), i, 5);
                model.setValueAt(f.getId_endereco().getEstado(), i, 6);
                model.setValueAt(f.getId_endereco().getCep(), i, 7);
                model.setValueAt(f.getId_endereco().getRua(), i, 8);
                model.setValueAt(f.getId_endereco().getNumero(), i, 9);
                model.setValueAt(f.getId_endereco().getBairro(), i, 10);
                
            }

            tableFarmacias.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmaciasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmaciasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmaciasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmaciasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmaciasJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelFarmacias;
    private javax.swing.JMenu labelIdioma;
    private javax.swing.JMenuBar menuIdioma;
    private javax.swing.JTable tableFarmacias;
    private javax.swing.JTextField textFieldBusca;
    // End of variables declaration//GEN-END:variables
}
